FROM hypriot/rpi-alpine-scratch

RUN apk update && \
apk upgrade && \
apk add python py-pip openssh-server && \
rm -rf /var/cache/apk/*

RUN pip install pexpect

EXPOSE 9090

ADD server.py /app/server.py

CMD ["python", "/app/server.py"]